development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ramais_development
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ramais_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ramais_producao
  pool: 5
  username: root
  password: root
  host: localhost